### PR TITLE
Changing timer to bimonthly.

### PR DESCRIPTION
**Pull request by mys721tx**
Changes timer to bimonthly per Let's Encrypt's recommendation.

### CODE REVIEW

**Comment by audeoudh** [comment]
Can we have a pointer to that “recommendation”?  I found a recommendation “on a regular basis, like every week or every day” (https://certbot.eff.org/docs/using.html#renewing-certificates), but nothing more.

**Comment by mys721tx** [comment]
[Here you go](https://letsencrypt.org/2015/11/09/why-90-days.html).

**Comment by audeoudh** [comment]
OK, thanks for the link.
- This article is too old to be a reference (they states that the “realize that our service is young”, and it is from 2015, older than resources just below).
- Some resources from 2016 indicates that [monthly is not frequent enough](https://serverfault.com/a/790776/448769) (and thus sixty days also), [here is clearly explained why](https://community.letsencrypt.org/t/solved-how-often-to-renew/13678/2).  I did not notice a change in instructions between 2016 and now.
- The proposed `OnCalendar=` instruction is for a 6 months renewal (see `systemd-analyze calendar --iterations=6 '*-1/6-0
1 00:00:00'`).

**Comment by mys721tx** [comment]
The [current FAQ](https://letsencrypt.org/docs/faq/) still recommends 60 days. I fixed the months to '*-1/2-01 00:00:00'.

**Comment by audeoudh** [comment]
OK, I understand now why they are talking of 60 days.

In both your links, they are talking about *certificates* that should be renewed every 60 days.  This is "effective" renewing, what `certbot renew --force-renewal` would do.

However, in my links, they are talking about when *cron jobs* should be run.  By default, `certbot renew` does nothing if certificates are recent enough: it looks at which certificates has a expiry date less than 30 days (90 days for initial validity time minus 60 days) and renews all those certificates.

Here, we are running cron jobs, so we should run `certbot renew` every day/week.

**Pull request closed without merging**
